# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5b60c9897c02c6e8bfc486d9347a063e8cbd9b9f36856dcaa2351598539ffb606b922941644ab62c419ebec3fc856320f10195b8ac956f5d8648a6b902c306f4

test:
  secret_key_base: ca8faff6d74dd864c99e1ef615cf3e515dd5b7235fd98ac7aa399c7f7c1041bfb05042a3d2274453d537cfe46647cccc946008a492c535c2e002830df71c76ff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
